package com.myspace.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Delivery implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "delivered")
	private java.lang.Boolean delivered;
	@org.kie.api.definition.type.Label(value = "DueDate")
	private java.util.Date dueDate;
	@org.kie.api.definition.type.Label(value = "deliveryDate")
	private java.util.Date deliveryDate;
	@org.kie.api.definition.type.Label(value = "deliveryMethod")
	private java.lang.String deliveryMethod;

	public Delivery() {
	}

	public java.lang.Boolean getDelivered() {
		return this.delivered;
	}

	public void setDelivered(java.lang.Boolean delivered) {
		this.delivered = delivered;
	}

	public java.util.Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.util.Date dueDate) {
		this.dueDate = dueDate;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public java.lang.String getDeliveryMethod() {
		return this.deliveryMethod;
	}

	public void setDeliveryMethod(java.lang.String deliveryMethod) {
		this.deliveryMethod = deliveryMethod;
	}

	public Delivery(java.lang.Boolean delivered, java.util.Date dueDate,
			java.util.Date deliveryDate, java.lang.String deliveryMethod) {
		this.delivered = delivered;
		this.dueDate = dueDate;
		this.deliveryDate = deliveryDate;
		this.deliveryMethod = deliveryMethod;
	}

}